name: pypi-test

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write  # Grant write permissions to the contents of the repository
    env:
      POETRY_VIRTUALENVS_CREATE: "false"
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: |
          pipx install poetry
          pipx inject poetry .

      - name: Increment patch version and set version with development release segment
        run: |
          bash scripts/dev_version_bump.sh

      - name: Build
        run: |
          poetry build

      - name: Publish package distributions to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/

      - name: Clear working changes and temporary files
        run: |
          git reset --hard
          git clean -fdx

      - name: Increment patch version and set version with development release segment again
        run: |
          bash scripts/dev_version_bump.sh

      - name: Commit version change
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "Set version to $NEW_VERSION"
          git push origin "${GITHUB_REF#refs/heads/}"
