name: Validate Markdown

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout aspire-virtues
      uses: actions/checkout@v2
      with:
        path: main
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: validate markdown with mdformat
      run: |
        pip install -U pip && \
          pip install mdformat-gfm mdformat-frontmatter && \
          mdformat --check --wrap 120 ./
