name: validation

on: [push, pull_request]

jobs:
  lint:
    name: lint / flake8
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: flake8
        uses: py-actions/flake8@v2
        with:
          max-line-length: "120"
      - name: black
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check --diff --line-length=120"
