name: validation

on: [push, pull_request]

jobs:
  lint:
    name: lint / python
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: black
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check --diff --line-length=120"
  build:
    name: lint / markdown
    runs-on: ubuntu-latest
    steps:
    - name: checkout aspire-virtues
      uses: actions/checkout@v2
      with:
        path: main
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: validate markdown with mdformat
      run: |
        pip install -U pip && \
          pip install mdformat-gfm mdformat-frontmatter && \
          mdformat --check --wrap 120 ./
